version: '2.3'

services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - fullstack-network

  frontend:
    image: azizmh98/frontend
    ports:
      - "8081:80"
    networks:
      - fullstack-network

  backend:
    image: azizmh98/backend
    ports:
      - "3000:3000"
    networks:
      - fullstack-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/StarServeur_db
    depends_on:
      - mongo

networks:
  fullstack-network:
    driver: bridge
