version: '2.3'

services:
  frontend:
    image: azizmh98/frontend
    ports:
      - "80:80"
    networks:
      - fullstack-network

  backend:
    image: azizmh98/backend
    ports:
      - "3000:3000"
    networks:
      - fullstack-network

networks:
  fullstack-network:
    driver: bridge
